version: "3.8"

services:
  web:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

# MongoDB configuration commented out for testing FastAPI alone
#  mongo:
#    image: mongo:5.0
#    container_name: mongo_db
#    restart: always
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
